### ISSUE TITLE
Issue since 1.20.2

### ISSUE THREAD

**Issue by GLeviathan** [gbl/EasierChests#21]
After updating to 1.20.2 it seems i cant open chests anymore without the game crashing.

Here is the code i get when it crashes:
The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: 'void de.guntram.mcmod.easierchests.ExtendedGuiChest.method_25420(net.minecraft.class_332)'

**Comment by gbl** [comment]
I'm on vacation right now. Will look into this when I'm back but it'll take a while.

**Comment by flyingitalianman** [comment]
any news on this?

**Comment by gbl** [comment]
A version for 1.20.4 is out now, should probably work on 1.20.3 as well.
